
* Release history

** main branch change

- ~aider-run-aider~ in dired, eshell, or shell buffer will ask if user wants to add `--subtree-only` flag
- Introduce AI assisted TDD, ~aider-tdd-cycle~, an experimental feature.

** v0.6.0

- Add ~aider-refactor-book-method~ and introduced couple of refactoring techniques from [[https://www.amazon.com/Refactoring-Improving-Existing-Addison-Wesley-Signature/dp/0134757599/ref=asc_df_0134757599?mcid=2eb8b1a5039a3b7c889ee081fc2132e0&hvocijid=16400341203663661896-0134757599-&hvexpln=73&tag=hyprod-20&linkCode=df0&hvadid=721245378154&hvpos=&hvnetw=g&hvrand=16400341203663661896&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9032161&hvtargid=pla-2281435180458&psc=1][Martin Flower's Refactoring book]]
- Enhance ~aider-plain-read-string~ with better completion and history
  - This came from https://github.com/MatthewZMD/aidermacs/commit/cbb9bada03681d7ab27ce3bce1c9be9e9469da99
- Deprecate +aider-other-process-command+ menu item. aider comint session already have command completion, so there is no advantage to use this menu item.
- Update keyword completion and highlight given aider in-chat commands change
- Added ~aider-core--auto-trigger-insert-prompt~. when ~aider-auto-trigger-prompt~ is t (default off), it will automatically trigger prompt insertion in aider comint session after one of the commands (/ask, /code, /architect).
- aider--comint-send-string-syntax-highlight use comint-send-input since it is a more standard way, given suggestion from Spike-Leung
- In aider-prompt-file, C-u C-c C-n can send block line by line in aider prompt file (close to C-c C-n)

** v0.5.5

- magit rebase style file operation in aider-prompt-mode, and send block line by line command (request from Spike-Leung) 
  - also added cycle between /ask and /architect command
- Remove redundant savehist configuration, by LemonBreezes (the history feature with savehist for aider-plain-read-string is initially added by LemonBreezes as well)
- aider-helm.el support candidate prompt list, aider-ask-question (Question on Context), aider-general-question (Question without Context) and aider-function-or-region-refactor (Change function / region) provide a list of prompt candidates respectively
  
- TODO keyword for aider-implement-todo is configurable through aider-todo-keyword-pair
- update aider-change-model to adapt recent aider change (three types of model command). For simplicity, only use the same aider-popular-models variable
- deprecate +aider-add-same-type-files-under-dir+, since things like /add *.el will do it
- deprecate +aider-fix-failing-test-under-cursor+. aider-function-or-region-refactor can do the same work.
- improve aider-write-unit-test by providing the option of write unit-test first given description (Test First)

- fix the issue: Chat window: wrap code always in code blocks: https://github.com/tninja/aider.el/issues/113
  - side effect: inhibited BOLD or italic text in regular markdown text outside of code block
- add aider-open-history function, under File section in the menu
- aider-function-or-region-refactor have different candidate-list for main code and test code

** v0.5.0

- Much improved aider-comint-mode rendering
  - Use color from markdown-mode.el. It support more than code block highlight
- Added Chinese version of README file
- Added to melpa. Updated install instruction

** v0.4.0

- User side change
  - Aider prompt file have
    - aider command syntax highlight
    - aider command completion
    - file name completion
    - prompt enter / completion from mini-buffer / helm
  - Aider session have
    - aider command completion
    - file name completion
    - prompt enter / completion from mini-buffer / helm

- Developer side change
  - Add aider-comint-mode major mode in aider-core.el, for aider comint buffer. It derived from comint-mode
  - Move aider command completion and file name completion to aider-core.el since they are used in both aider prompt file and aider comint buffer

** v0.3.0

- User side change
  - Menu: Simplify menu to make it fit the screen: Thanks Spike-Leung
    - Group operations into same menu item. Less used one bind to C-u
    - https://github.com/tninja/aider.el/pull/93
  - Improve the mini buffer prompt re-usability
    - Make the use entered prompt in history more reusable across project.
    - Highly recommend to use aider-helm.el for better prompt history search experience.
    - https://github.com/tninja/aider.el/pull/94
  - Add snippets support to aider prompt file
    - Initial snippet came from reddit user LorestForest
    - https://github.com/tninja/aider.el/pull/101

- Developer side change
  - https://github.com/tninja/aider.el/pull/101
  - Deprecate aider-minor-mode, use aider-prompt-mode (major-mode) instead
    - aider-prompt-mode inherit from org-mode
  - Large refactoring to aider.el, break it into several small files, to help future development and maintaining
    - aider-core.el: core comint aider session interaction function
      - also have customize variables
    - aider-file.el: file operation related functions
      - depend on aider-core.el
    - aider-code-change.el: code change related functions
      - depend on aider-core.el and aider-file.el
    - aider-discussion.el: discussion related functions
      - depend on aider-core.el and aider-file.el
    - aider-prompt-mode.el: major mode for aider prompt file
      - depend on aider-core
    - aider.el: aider session management and transient menu
      - depend on files all above
