
* Introduce of the project

Recently, My son play the [[https://en.wikipedia.org/wiki/Battleship_(game)][Battle Ship board game]] with me, this is a game with 90 years history. My son enjoy this.

- [[https://www.amazon.com/dp/B06Y1N3PTX?ref=ppx_yo2ov_dt_b_fed_asin_title&th=1][Amazon link to Battle Ship Game]], it is still top 20 of board game in Amazon.

I thought it would be a interesting to implement the game in Python, with help of aider (and aider.el).

The implementation took totally around 4 hours to have a human player vs a pretty good computer player.

Most of the code were written by aider + deepseek model (price is 1% of chatgpt, but it is a little bit slow) (~3 hour)

The Computer Player AI part was written by new published anthropic/claude-3-5-sonnet-20241022 model, and aider support that. (~1 hour)

* Game Design 

** Data structure

*** Fleet
  - list of (x, y) coordinates
    - every x, y must be
      - inside the board (0 <= x < 10, 0 <= y < 10)
      - unique
      - adjacent to each other
      - in the same direction
      - x, y are generated by the init function below
  - name: choice of carrier, battleship, cruiser, submarine, destroyer
  - init(x, y, size, direction, name)
    - size: 2, 3, 4, 5
    - direction: horizontal or vertical
  - hit(x, y)
    - return true if the hit is successful
    - log the hit point
  - is_sunk()
    - return true if the fleet is sunk

*** FleetGroup
  - list of Fleet
  - init(): create empty fleet group
  - add(fleet): add a fleet to the group
  - hit(x, y)
    - return the fleet name if the hit is successful
    - return None if the hit is failed
  - all_sunk()
    - return true if all fleets are sunk

*** Player 
  - fleetGroup
  - hitHistory
    - list of (x, y, is_hit)
  - randomInit(fleetNames=['carrier', 'battleship', 'cruiser', 'submarine', 'destroyer'], boardSize=(10, 10))
    - randomly place n fleets on the board
      - n is the size of fleetNames
    - fleets cannot overlap each other
    - fleet must be inside board
  - hit(player, x, y)
    - return true if the hit is successful on the player's fleet
    - return false if the hit is failed
    - log x, y, is_hit to hitHistory
  - was_hit(x, y)
    - return the fleet name if the hit is successful
    - return None if the hit is failed
  - all_sunk()
    - return true if all fleets are sunk

**** Human Player
  - input_and_hit(player)
     - get x, y from the user
     - call player.hit(x, y)

**** Computer Player       
  - input_and_hit(player)
     - smartly choose x, y based on hit history and boat size of the player
     - call player.hit(x, y)

*** Game
  - init(fleetNames, boardSize)
  - addPlayers(player1, player2)
  - run()
    - loop until one of the players' all fleets are sunk
      - player1 hit player2
      - player2 hit player1
    - print the winner
  - two_player_games()
    - create player1 and player2 with HumanPlayer and randomInit and addPlayers(player1, player2)
    - run()




* Background: [[https://en.wikipedia.org/wiki/Battleship_(game)][Battleship game (wiki)]]

- The following information are provided to aider during implementation.

Battleship (also known as Battleships) is a strategy type guessing game for two players. It is played on ruled grids (paper or board) on which each player's fleet of warships are marked. The locations of the fleets are concealed from the other player. Players alternate turns calling "shots" at the other player's ships, and the objective of the game is to destroy the opposing player's fleet.

Battleship is known worldwide as a pencil and paper game which dates from World War I. It was published by various companies as a pad-and-pencil game in the 1930s and was released as a plastic board game by Milton Bradley in 1967. The game has spawned electronic versions, video games, smart device apps and a film.
History

The game of Battleship is thought to have its origins in the French game L'Attaque played during World War I, although parallels have also been drawn to E. I. Horsman's 1890 game Basilinda,[1] and the game is said to have been played by Russian officers before World War I.[3] In 1907 the game playing was mentioned in the diary of Russian poet Ryurik Ivnev.[4] The first commercial version of the game was Salvo, published in 1931 in the United States by the Starex company. Other versions of the game were printed in the 1930s and 1940s, including the Strathmore Company's Combat: The Battleship Game, Milton Bradley's Broadsides: A Game of Naval Strategy and Maurice L. Freedman's Warfare Naval Combat. Strategy Games Co. produced a version called Wings which pictured planes flying over the Los Angeles Coliseum. All of these early editions of the game consisted of pre-printed pads of paper.[1]
A map of one player's ships and the hits against them, from a game in progress. The grey boxes are the ships placed by the player, and the cross marks show the squares that their opponent has fired upon. The player would be tracking the success of their own shots in a separate grid

In 1967 Milton Bradley introduced a version of the game that used plastic boards and pegs. Conceived by Ed Hutchins, play was on pegboards using miniature plastic ships. In 1977, Milton Bradley also released a computerized Electronic Battleship,[5] a pioneering microprocessor-based toy, capable of generating various sounds.[6] Electronic Battleship was designed by Dennis Wyman and Bing McCoy.[citation needed] It was followed in 1989 by Electronic Talking Battleship.[7] In 2008, an updated version of Battleship was released, using hexagonal tiles. In the updated version, each player's board contains several islands on which "captured man" figurines can be placed. Ships may be placed only around the islands, and only in the player's half of the board. When the movie Battleship was released, the board game reverted to the original 1967 style. The 2008 updated version is still available as Battleship Islands.

Battleship was one of the earliest games to be produced as a computer game, with a version being released for the Z80 Compucolor in 1979.[1][8] Many computer editions of the game have been produced since. In Clubhouse Games for the Nintendo DS, Battleship is known as Grid Attack.[9] It is played on a 7×7 grid,[10] and includes slight variations, such as four-player gameplay, and various ship sizes and shapes. Versions of Battleship appear as applications on numerous social networking services.

Battleship was also part of Hasbro Family Game Night for the PlayStation 2 and Wii, as well as the Xbox 360 (Xbox Live Arcade). These alter the rules, including the size of the grid (8×12 in the NES version, 8×8 in the Game Boy version), size of ships (it is common to feature a submarine that takes up a single square) and special shot missiles for each ship. For example, in the NES version, the cruiser has a five-shot missile which strikes five squares in an X pattern on the grid in one turn. Submarine-tracking sonar and aerial reconnaissance to spot ships are also features.

A minigame version of Battleship was used in the third season of The Hub's Family Game Night, which uses a 5×5 grid and the first team to sink three ships wins the game.

In 2012, the military science fiction action movie Battleship was released, which was inspired by the Milton Bradley board game, which this adaptation is an alien invasion-theme movie. A version of Battleship based on the movie was released in which one side had alien ship playing pieces.

In 1973 a spin-off version was released under the name Sub Search. Employing a three-dimensional play area, battleships drop depth charges on submarines hidden on a multi-level board.

In one episode of the Amazon Prime Video show The Grand Tour, presenters Richard Hammond and James May played a game of Battleship with two cranes (colored red and green) and 20 REVAi vehicles as missiles. The ships ranged from cars to campervans. May won the game after sinking all of Hammond's ships.
Description

The game is played on four grids, two for each player. The grids are typically square, usually 10×10, and the individual squares in the grid are identified by letter and number.[11] On one grid the player arranges ships and records the shots by the opponent. On the other grid, the player records their own shots.

Before play begins, each player secretly arranges their ships on their primary grid. Each ship occupies a number of consecutive squares on the grid, arranged either horizontally or vertically. The number of squares for each ship is determined by the type of ship. The ships cannot overlap (i.e., only one ship can occupy any given square in the grid) or be placed diagonally. The types and numbers of ships allowed are the same for each player. These may vary depending on the rules. The ships should be hidden from the opposing player's sight and players are not allowed to see each other's pieces. The game is a discovery game in which players need to discover their opponent's ship positions.[12]

The 1990 Milton Bradley version of the rules specify the following ships:[13]
No. 	Class of ship 	Size
1 	Carrier 	5
2 	Battleship 	4
3 	Cruiser 	3
4 	Submarine 	3
5 	Destroyer 	2

In 2002, Hasbro renamed the Cruiser to Destroyer, taking three squares, and introduced a new two-square ship called the Patrol Boat.[14]
No. 	Class of ship 	Size
1 	Carrier 	5
2 	Battleship 	4
3 	Destroyer 	3
4 	Submarine 	3
5 	Patrol Boat 	2

After the ships have been positioned, the game proceeds in a series of rounds. In each round, each player takes a turn to announce a target square in the opponent's grid which is to be shot at. The opponent announces whether or not the square is occupied by a ship. If it is a "hit", the player who is hit marks this on their own "ocean" or grid (with a red peg in the pegboard version), and announces what ship was hit. The attacking player marks the hit or miss on their own "tracking" or "target" grid with a pencil marking in the paper version of the game, or the appropriate color peg in the pegboard version (red for "hit", white for "miss"), in order to build up a picture of the opponent's fleet.

When all of the squares of a ship have been hit, the ship's owner announces the sinking of the Carrier, Submarine, Cruiser/Destroyer/Patrol Boat, or the titular Battleship. If all of a player's ships have been sunk, the game is over and their opponent wins.
Variations
Players in a Battleship tournament aboard USS George H.W. Bush

In the 1931 Salvo edition of the game, players target a specified number of squares at one time, and all of the squares are attacked simultaneously. A player may initially target five (one for each unsunken ship) squares per turn, and the amount of shots decreases when one of the player's ships are lost.[3] In other variants of this mechanic, the number of shots allowed to fire each turn may either be fixed at five for the whole game, be equal to the number of unsunken ships belonging to the player, or be equal to the size of the player's largest undamaged ship.[1] The opponent may either call the result of each shot in turn or simply announce the hits or misses. E.g.: "two hits and three misses", leaving their opponent to work out the consequences of the salvo.[1] In the modern Milton Bradley rules for Battleship, Salvo is listed as a variation "for more experienced players", with the number of shots being equal to the number of ships that the firing player has remaining.[13]

One variant of Battleship allows players to decline to announce that a ship has been sunk, requiring their opponent to take further shots in order to confirm that an area is clear.[1] Another variant of the rule allows a player to move one of their ships to a new, uncalled location every fourth or fifth move.[1]
Reviews

    Family Games: The 100 Best[15]

See also

    Battleship (film), 2012 film adaptation
    Battleship (puzzle)
    Video game adaptations:
        Battleships, 1987, for ZX Spectrum, Commodore 64, Amstrad CPC, BBC Micro, and Amiga computers
        Battleship, 1993, for Nintendo Entertainment System and Game Gear systems
        Super Battleship, 1993, for Genesis and Super NES systems
        Battleship, 1996, for PCs
        Battleship: Surface Thunder, 2000, for PCs
        Battleship, a 2012 tie-in to the film above, for PlayStation 3, Xbox 360, Wii, Nintendo DS, and Nintendo 3DS
    Similar games:
        Minesweeper, logic puzzle video game genre
        Mugwump, 1973 computer game
    Wargame, strategy game genre

